apiVersion: {{ .Values.apiVersion }}
kind: Deployment
metadata:
  name: {{ include "name" . | quote }}
  labels:
    component: app
{{ include "helm-labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: app
{{ include "common-labels" . | indent 6 }}
  template:
    metadata:
      labels:
        component: app
{{ include "common-labels" . | indent 8 }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
{{- if .Values.rbac.install }}
      serviceAccountName: {{ include "name" . | quote }}
{{- end }}
      containers:
      - name: "{{ .Values.containerName }}"
        image: {{ include "image" . | quote }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: 9710
          name: metrics
          protocol: TCP
