[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.5.6"

[[constraint]]
  name = "github.com/sirupsen/logrus"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.7"

[[constraint]]
  name = "k8s.io/client-go"
  version = "4.0.0"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.7"

# This is due to an issue with k8s.io/client-go and dep not
# being able to lock transient dependencies
[[override]]
  name = "github.com/ugorji/go"
  revision = "8c0409fcbb70099c748d71f714529204975f6c3f"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"
