apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
  redis:
    replicas: 3
    exporter: 
      enabled: true
      image: oliver006/redis_exporter:v0.33.0