name: CI

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    # Execute the checks inside the container instead the VM.
    container: golangci/golangci-lint:v1.43.0-alpine
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/check.sh

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: make ci-unit-test

  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install conntrack
        run: sudo apt-get install -y conntrack
      - uses: medyagh/setup-minikube@v0.0.7
        with:
          kubernetes-version: 1.22.2
          driver: none
      - run: make ci-integration-test
